### ISSUE TITLE
Έλλειψη ενός Διαγράμματος Nyquist

### ISSUE THREAD

**Issue by tasoskakour** [kongr45gpen/ece-notes#13]
Καλησπέρα, νομίζω πώς στη σελίδα 59 στο last updated pdf, στην άσκηση που αρχίζει στο τέλος της σελίδας λείπει ένα διάγραμμα Nyquist (στο οποίο αναφέρεται η συγκεκριμένη άσκηση).

Εκπληκτική δουλειά btw, keep it up 👍  :)

**Comment by kongr45gpen** [comment]
Πρέπει να έχει προστεθεί!
